//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app.domain.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("app.domain.Languages.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haqqımızda.
        /// </summary>
        public static string AboutUsText {
            get {
                return ResourceManager.GetString("AboutUsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ünvan.
        /// </summary>
        public static string AddressText {
            get {
                return ResourceManager.GetString("AddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilk bölmənizi yaradın.
        /// </summary>
        public static string AddYourFirstSectionText {
            get {
                return ResourceManager.GetString("AddYourFirstSectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müəllim ol.
        /// </summary>
        public static string BecomeInstructorText {
            get {
                return ResourceManager.GetString("BecomeInstructorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imtina.
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kateqoriya.
        /// </summary>
        public static string CategoryText {
            get {
                return ResourceManager.GetString("CategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to təsdiqləndi. Təşəkkürər!.
        /// </summary>
        public static string CinfirmSuccessMessagePart {
            get {
                return ResourceManager.GetString("CinfirmSuccessMessagePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qeyd.
        /// </summary>
        public static string CommentText {
            get {
                return ResourceManager.GetString("CommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Təkrar şifrə.
        /// </summary>
        public static string ConfirmPasswordText {
            get {
                return ResourceManager.GetString("ConfirmPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizimlə əlaqə.
        /// </summary>
        public static string ContactUsText {
            get {
                return ResourceManager.GetString("ContactUsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video yükləyin.
        /// </summary>
        public static string CourseAddVideoText {
            get {
                return ResourceManager.GetString("CourseAddVideoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Təsdiqlənib.
        /// </summary>
        public static string CourseApprovedStatusText {
            get {
                return ResourceManager.GetString("CourseApprovedStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurs yaradın.
        /// </summary>
        public static string CourseCreateText {
            get {
                return ResourceManager.GetString("CourseCreateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ümumi məlumat.
        /// </summary>
        public static string CourseDescriptionText {
            get {
                return ResourceManager.GetString("CourseDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kursun detalları.
        /// </summary>
        public static string CourseDetailsTitleText {
            get {
                return ResourceManager.GetString("CourseDetailsTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natamam.
        /// </summary>
        public static string CourseDraftStatusText {
            get {
                return ResourceManager.GetString("CourseDraftStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kursu dəyiş.
        /// </summary>
        public static string CourseEditTitleText {
            get {
                return ResourceManager.GetString("CourseEditTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kursun adı.
        /// </summary>
        public static string CourseNameText {
            get {
                return ResourceManager.GetString("CourseNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göndərilib.
        /// </summary>
        public static string CourseSentStatusText {
            get {
                return ResourceManager.GetString("CourseSentStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurs.
        /// </summary>
        public static string CourseText {
            get {
                return ResourceManager.GetString("CourseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kursa baxış.
        /// </summary>
        public static string CourseViewText {
            get {
                return ResourceManager.GetString("CourseViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az.
        /// </summary>
        public static string CurrentLanguage {
            get {
                return ResourceManager.GetString("CurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redaktə.
        /// </summary>
        public static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-LearningHub izləyin.
        /// </summary>
        public static string EmailBodyFooterTitle1 {
            get {
                return ResourceManager.GetString("EmailBodyFooterTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçilərin Yardım Mərkəzi.
        /// </summary>
        public static string EmailBodyFooterTitle2 {
            get {
                return ResourceManager.GetString("EmailBodyFooterTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Ünvanını Təsdiqləyin.
        /// </summary>
        public static string EmailConfirmationMailBodyButton3 {
            get {
                return ResourceManager.GetString("EmailConfirmationMailBodyButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hörmətlə,.
        /// </summary>
        public static string EmailConfirmationMailBodyBye5 {
            get {
                return ResourceManager.GetString("EmailConfirmationMailBodyBye5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xahiş edirik, bir saniyənizi ayırıb.
        /// </summary>
        public static string EmailConfirmationMailBodyConfirmPart21 {
            get {
                return ResourceManager.GetString("EmailConfirmationMailBodyConfirmPart21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email ünvanını sizin düzgün ünvanınız kimi təsdiqləyəsiniz:.
        /// </summary>
        public static string EmailConfirmationMailBodyConfirmPart22 {
            get {
                return ResourceManager.GetString("EmailConfirmationMailBodyConfirmPart22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salam.
        /// </summary>
        public static string EmailConfirmationMailBodyHi1 {
            get {
                return ResourceManager.GetString("EmailConfirmationMailBodyHi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əgər yuxarıda verilən düyməni işlətməkdə çətinlik çəkirsinizsə, siz, həmçinin, aşağıda verilmiş linkə klinkləyin:.
        /// </summary>
        public static string EmailConfirmationMailBodyIf4 {
            get {
                return ResourceManager.GetString("EmailConfirmationMailBodyIf4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əgər siz qeydiyyatdan keçməmisinizsə və ya email ünvanını təsdiqləmək üçün tələb göndərməmisinizsı, o halda bu emaildən imtina edin..
        /// </summary>
        public static string EmailConfirmationMailBodyText7 {
            get {
                return ResourceManager.GetString("EmailConfirmationMailBodyText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tələb olunur: Xahiş edirik email ünvanınızı təqsdiqləyəsiniz.
        /// </summary>
        public static string EmailConfirmationMailSubject {
            get {
                return ResourceManager.GetString("EmailConfirmationMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoş e-Təlimlər!.
        /// </summary>
        public static string EmailMailBodyHappy {
            get {
                return ResourceManager.GetString("EmailMailBodyHappy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizin e-LearningHub Komandası.
        /// </summary>
        public static string EmailMailBodyTeam {
            get {
                return ResourceManager.GetString("EmailMailBodyTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gəlin Başlayaq.
        /// </summary>
        public static string EmailRegisteredMailBodyButtonText7 {
            get {
                return ResourceManager.GetString("EmailRegisteredMailBodyButtonText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salam.
        /// </summary>
        public static string EmailRegisteredMailBodyHi1 {
            get {
                return ResourceManager.GetString("EmailRegisteredMailBodyHi1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Təbriklər! Siz, biliklərinizi gücləndirmək və karyeranızda yüksəlmək üçün irəliyə doğru çox mühim bir addım atdınız!.
        /// </summary>
        public static string EmailRegisteredMailBodyText1 {
            get {
                return ResourceManager.GetString("EmailRegisteredMailBodyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçilərin Yardım Mərkəzi.
        /// </summary>
        public static string EmailRegisteredMailBodyText10 {
            get {
                return ResourceManager.GetString("EmailRegisteredMailBodyText10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siz bu emaili alırsınız, çünki e-LearningHub saytında qeydiyyatdan keçmisiniz..
        /// </summary>
        public static string EmailRegisteredMailBodyText11 {
            get {
                return ResourceManager.GetString("EmailRegisteredMailBodyText11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-LearningHub saytının təmin etdiyi hər bir təlim 100% onlayndır. Biz, sizin öyrənərək yüksəlməyiniz və mevəffəqiyyətli olmağınız üçün sizi lazımlı təlim və dərslərlə təmin edirik. Siz artıq öz dəyərli vaxtınızı təlim mərkəzlərinə çatmaq üçün yollarda sərf etməyəcəksiniz. Bundan sonra, yalnız uyğun vaxtda sizə servis göstərmək üçün biz burdayıq! Sadəcə olaraq, arxanıza yastlanın və öz rahat divanınızda onlayn təlimlərdən yararlanın!.
        /// </summary>
        public static string EmailRegisteredMailBodyText2 {
            get {
                return ResourceManager.GetString("EmailRegisteredMailBodyText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizin üçün, Bizdən!.
        /// </summary>
        public static string EmailRegisteredMailBodyText3 {
            get {
                return ResourceManager.GetString("EmailRegisteredMailBodyText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saytdakı qeydiyyatınızı 10% endirim ilə bayram edin!.
        /// </summary>
        public static string EmailRegisteredMailBodyText4 {
            get {
                return ResourceManager.GetString("EmailRegisteredMailBodyText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROMO KOD:.
        /// </summary>
        public static string EmailRegisteredMailBodyText5 {
            get {
                return ResourceManager.GetString("EmailRegisteredMailBodyText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etibarlıdır.
        /// </summary>
        public static string EmailRegisteredMailBodyText6 {
            get {
                return ResourceManager.GetString("EmailRegisteredMailBodyText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saytımızdan alacağınız ilk təlim üçün sizə 10% endirim.
        /// </summary>
        public static string EmailRegisteredMailDiscountText {
            get {
                return ResourceManager.GetString("EmailRegisteredMailDiscountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-LearningHub`a xoş gəldiniz.
        /// </summary>
        public static string EmailRegisteredMailSubject {
            get {
                return ResourceManager.GetString("EmailRegisteredMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrənizi yeniləyin.
        /// </summary>
        public static string EmailResetMailBodyButtonText {
            get {
                return ResourceManager.GetString("EmailResetMailBodyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hörmətlə,.
        /// </summary>
        public static string EmailResetMailBodyBye {
            get {
                return ResourceManager.GetString("EmailResetMailBodyBye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salam.
        /// </summary>
        public static string EmailResetMailBodyHi {
            get {
                return ResourceManager.GetString("EmailResetMailBodyHi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-LearningHub Texniki Dəstək Komandası.
        /// </summary>
        public static string EmailResetMailBodyTechnicalTeam {
            get {
                return ResourceManager.GetString("EmailResetMailBodyTechnicalTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biz sizdən e-LearningHub hesabınızın şifrəsini yeniləmək barədə tələb aldıq..
        /// </summary>
        public static string EmailResetMailBodyText {
            get {
                return ResourceManager.GetString("EmailResetMailBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrənizi yeniləmək üçün, xahiş edirik, aşağıdakı düyməni sıxın.
        /// </summary>
        public static string EmailResetMailBodyText2 {
            get {
                return ResourceManager.GetString("EmailResetMailBodyText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternativ olaraq, siz aşağıdakı keçidi brauzerin ünvan yazılan xanasına köçürərək şifrənizi yeniləyə bilərsiniz:.
        /// </summary>
        public static string EmailResetMailBodyText3 {
            get {
                return ResourceManager.GetString("EmailResetMailBodyText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qeyd: Bu keçid növbəti 24 saatdan sonra etibarsız sayılacaqdır və yalnız bir dəfə istifadə oluna bilər..
        /// </summary>
        public static string EmailResetMailBodyText4 {
            get {
                return ResourceManager.GetString("EmailResetMailBodyText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizə möhkəm yaddaş arzulayırıq!.
        /// </summary>
        public static string EmailResetMailBodyText5 {
            get {
                return ResourceManager.GetString("EmailResetMailBodyText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrənizi yeniləyin.
        /// </summary>
        public static string EmailResetMailSubject {
            get {
                return ResourceManager.GetString("EmailResetMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zəhmət olmasa, davam etmək üçün Qaydaları və Şərtləri qəbul edin.
        /// </summary>
        public static string ErrorIsAgreeTerms {
            get {
                return ResourceManager.GetString("ErrorIsAgreeTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  məşğuldur.
        /// </summary>
        public static string ErrorIsBusyText {
            get {
                return ResourceManager.GetString("ErrorIsBusyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to simvolları. .
        /// </summary>
        public static string ErrorIsIncorrectSymbolText {
            get {
                return ResourceManager.GetString("ErrorIsIncorrectSymbolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  yalnışdır. .
        /// </summary>
        public static string ErrorIsIncorrectText {
            get {
                return ResourceManager.GetString("ErrorIsIncorrectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  seçilməyib..
        /// </summary>
        public static string ErrorIsNotSelected {
            get {
                return ResourceManager.GetString("ErrorIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  maximum uzunluq: .
        /// </summary>
        public static string ErrorMaximumLengthText {
            get {
                return ResourceManager.GetString("ErrorMaximumLengthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum uzunluq: .
        /// </summary>
        public static string ErrorMinimumLengthText {
            get {
                return ResourceManager.GetString("ErrorMinimumLengthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail göndərilməsində xəta baş verdi.
        /// </summary>
        public static string ErrorOnMailSending {
            get {
                return ResourceManager.GetString("ErrorOnMailSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , minimum bir rəqəm, bir kiçik, bir böyük hərf və bir simvol istifadə edin.
        /// </summary>
        public static string ErrorPasswordMinimumRequirment {
            get {
                return ResourceManager.GetString("ErrorPasswordMinimumRequirment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirfrələr eyni deyil.
        /// </summary>
        public static string ErrorPasswordsNotSameText {
            get {
                return ResourceManager.GetString("ErrorPasswordsNotSameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol yalnışdır..
        /// </summary>
        public static string ErrorRoleIsIncorrectText {
            get {
                return ResourceManager.GetString("ErrorRoleIsIncorrectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Istifadə edilməlidir:.
        /// </summary>
        public static string ErrorUseOnlyText {
            get {
                return ResourceManager.GetString("ErrorUseOnlyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi tapılmadı.
        /// </summary>
        public static string ErrorUserNotFound {
            get {
                return ResourceManager.GetString("ErrorUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistem xətası.
        /// </summary>
        public static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FB link.
        /// </summary>
        public static string FBLinkText {
            get {
                return ResourceManager.GetString("FBLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirfrəni unutdun?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yardım &amp; Dəstək.
        /// </summary>
        public static string HelpAndSupportText {
            get {
                return ResourceManager.GetString("HelpAndSupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana səhifə.
        /// </summary>
        public static string HomeText {
            get {
                return ResourceManager.GetString("HomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şərtlərlə razıyam.
        /// </summary>
        public static string IAgreeTermsAndConditions {
            get {
                return ResourceManager.GetString("IAgreeTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məlumat uğurla saxlanıldı.
        /// </summary>
        public static string InformationSavedSuccessfully {
            get {
                return ResourceManager.GetString("InformationSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ümumi məlumat.
        /// </summary>
        public static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müəllim.
        /// </summary>
        public static string InstructorText {
            get {
                return ResourceManager.GetString("InstructorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maraqlandığım kateqoriya.
        /// </summary>
        public static string InterestedCategoryText {
            get {
                return ResourceManager.GetString("InterestedCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azərbaycan.
        /// </summary>
        public static string LanguageName {
            get {
                return ResourceManager.GetString("LanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        public static string LanguageText {
            get {
                return ResourceManager.GetString("LanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tələbə.
        /// </summary>
        public static string LearnerText {
            get {
                return ResourceManager.GetString("LearnerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linkedin link.
        /// </summary>
        public static string LinkedinLinkText {
            get {
                return ResourceManager.GetString("LinkedinLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail uğurla göndərildi.
        /// </summary>
        public static string MailSentMessageSuccess {
            get {
                return ResourceManager.GetString("MailSentMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müəllimlərimizlə tanış olun.
        /// </summary>
        public static string MeetOurInstructorsText {
            get {
                return ResourceManager.GetString("MeetOurInstructorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesab məlumatları.
        /// </summary>
        public static string MenuAccountInformation {
            get {
                return ResourceManager.GetString("MenuAccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrəni dəyiş.
        /// </summary>
        public static string MenuChangePasswordText {
            get {
                return ResourceManager.GetString("MenuChangePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əlaqə.
        /// </summary>
        public static string MenuContact {
            get {
                return ResourceManager.GetString("MenuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mənim E-otağım.
        /// </summary>
        public static string MenuERoomText {
            get {
                return ResourceManager.GetString("MenuERoomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana səhifə.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil telefon.
        /// </summary>
        public static string MobileText {
            get {
                return ResourceManager.GetString("MobileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mənim hesabım.
        /// </summary>
        public static string MyAccountText {
            get {
                return ResourceManager.GetString("MyAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurslarım.
        /// </summary>
        public static string MyCoursesText {
            get {
                return ResourceManager.GetString("MyCoursesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Təsdiqlənmiş yeni şifrə.
        /// </summary>
        public static string NewPasswordConfirmText {
            get {
                return ResourceManager.GetString("NewPasswordConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrənin yenilənməsi.
        /// </summary>
        public static string NewPasswordPanelTitle {
            get {
                return ResourceManager.GetString("NewPasswordPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni şifrə.
        /// </summary>
        public static string NewPasswordText {
            get {
                return ResourceManager.GetString("NewPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Köhnə şifrə.
        /// </summary>
        public static string OldPasswordText {
            get {
                return ResourceManager.GetString("OldPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to və ya.
        /// </summary>
        public static string OrText {
            get {
                return ResourceManager.GetString("OrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoşbəxt müştərilərimiz.
        /// </summary>
        public static string OurHappyClientsText {
            get {
                return ResourceManager.GetString("OurHappyClientsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müəllimlərimiz.
        /// </summary>
        public static string OurInstructorsText {
            get {
                return ResourceManager.GetString("OurInstructorsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizim təklifimiz.
        /// </summary>
        public static string OurOfferText {
            get {
                return ResourceManager.GetString("OurOfferText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bacarıqlarımız.
        /// </summary>
        public static string OurSkillsText {
            get {
                return ResourceManager.GetString("OurSkillsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komandamız.
        /// </summary>
        public static string OurTeamText {
            get {
                return ResourceManager.GetString("OurTeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vizyonumuz.
        /// </summary>
        public static string OurVisionText {
            get {
                return ResourceManager.GetString("OurVisionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Səhifə tapılmadı.
        /// </summary>
        public static string PageNotFoundText {
            get {
                return ResourceManager.GetString("PageNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrəniz uğurla dəyişdirildi.
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrəniz uğurla dəyişdirildi.
        /// </summary>
        public static string PasswordChangedSuccessfullyText {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfullyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrə.
        /// </summary>
        public static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string PhoneText {
            get {
                return ResourceManager.GetString("PhoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vəzifə.
        /// </summary>
        public static string PositionText {
            get {
                return ResourceManager.GetString("PositionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qiymət.
        /// </summary>
        public static string PriceText {
            get {
                return ResourceManager.GetString("PriceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tez əlaqə.
        /// </summary>
        public static string QuickContactText {
            get {
                return ResourceManager.GetString("QuickContactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabınızı aktivləşdirmək üçün keçid sizin email ünvanınıza göndərildi. Xahiş edirik, email ünvanınızdakı gələnlər qutusuna keçib aktivləşdirməni tamamlayasınız..
        /// </summary>
        public static string RegisteredPageContent {
            get {
                return ResourceManager.GetString("RegisteredPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hörmətli.
        /// </summary>
        public static string RegisteredPageTitle {
            get {
                return ResourceManager.GetString("RegisteredPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qeydiyyat.
        /// </summary>
        public static string RegisterSubmitButton {
            get {
                return ResourceManager.GetString("RegisterSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yadda saxla.
        /// </summary>
        public static string RememberPassword {
            get {
                return ResourceManager.GetString("RememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məcburi xanalar.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girişə qayıt.
        /// </summary>
        public static string ResetBackLoginText {
            get {
                return ResourceManager.GetString("ResetBackLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biz şifrənizi yeniləmək üçün keçidi.
        /// </summary>
        public static string ResetLinkSentPageInfoPart1 {
            get {
                return ResourceManager.GetString("ResetLinkSentPageInfoPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ünvanına göndərdik..
        /// </summary>
        public static string ResetLinkSentPageInfoPart2 {
            get {
                return ResourceManager.GetString("ResetLinkSentPageInfoPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizdən emaili alanda, orada verilmiş düyməyə sıxaraq şifrənizi yeniləyə bilərsiniz..
        /// </summary>
        public static string ResetLinkSentPageInfoPart3 {
            get {
                return ResourceManager.GetString("ResetLinkSentPageInfoPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əgər bir neçə dəqiqə ərzində bizdən email almasanız, bu halda, xahiş edirik, spam qovluğunu yoxlayasınız..
        /// </summary>
        public static string ResetLinkSentPageInfoPart4 {
            get {
                return ResourceManager.GetString("ResetLinkSentPageInfoPart4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xahiş edirik, email ünvanınızı aşağıdakı xanaya daxil edin. Biz sizin hesabınızı tapıb şifrənizi yeniləmək üçün sizə uyğun keçidi göndərəcəyik..
        /// </summary>
        public static string ResetPanelInfo {
            get {
                return ResourceManager.GetString("ResetPanelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrənizi yeniləyin.
        /// </summary>
        public static string ResetPanelTitle {
            get {
                return ResourceManager.GetString("ResetPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uğurlar.
        /// </summary>
        public static string ResetPasswordMailBody6 {
            get {
                return ResourceManager.GetString("ResetPasswordMailBody6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siz e-LearningHub saytındakı hesabınızda şifrənizi yeniləmək üçün sorğu göndərmisiniz.
        /// </summary>
        public static string ResetPasswordMailBodyAccount3 {
            get {
                return ResourceManager.GetString("ResetPasswordMailBodyAccount3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrəni yeniləyin.
        /// </summary>
        public static string ResetPasswordMailBodyButton5 {
            get {
                return ResourceManager.GetString("ResetPasswordMailBodyButton5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narahat olmayın, biz də hərdən unuda bilirik.
        /// </summary>
        public static string ResetPasswordMailBodyForget1 {
            get {
                return ResourceManager.GetString("ResetPasswordMailBodyForget1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salam.
        /// </summary>
        public static string ResetPasswordMailBodyHi2 {
            get {
                return ResourceManager.GetString("ResetPasswordMailBodyHi2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrənizi yeniləmək üçün aşağıdakı düyməyə klikləyin.
        /// </summary>
        public static string ResetPasswordMailBodyUpdate4 {
            get {
                return ResourceManager.GetString("ResetPasswordMailBodyUpdate4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrənin yenilənməsi.
        /// </summary>
        public static string ResetPasswordMailSubject {
            get {
                return ResourceManager.GetString("ResetPasswordMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-LearningHub Komandası.
        /// </summary>
        public static string ResetPasswordMailTeam7 {
            get {
                return ResourceManager.GetString("ResetPasswordMailTeam7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrəni göndər.
        /// </summary>
        public static string ResetSubmitButton {
            get {
                return ResourceManager.GetString("ResetSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saxla.
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölmə yaradın.
        /// </summary>
        public static string SectionAddVideoText {
            get {
                return ResourceManager.GetString("SectionAddVideoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni bölmə adı.
        /// </summary>
        public static string SectionCreateNewText {
            get {
                return ResourceManager.GetString("SectionCreateNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bölmə seçin.
        /// </summary>
        public static string SectionSelectText {
            get {
                return ResourceManager.GetString("SectionSelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Təsdiqə göndər.
        /// </summary>
        public static string SendForApproval {
            get {
                return ResourceManager.GetString("SendForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesaba giriş.
        /// </summary>
        public static string SignInPanelTitle {
            get {
                return ResourceManager.GetString("SignInPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daxil ol.
        /// </summary>
        public static string SigninSubmitButton {
            get {
                return ResourceManager.GetString("SigninSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daxil ol.
        /// </summary>
        public static string SigninText {
            get {
                return ResourceManager.GetString("SigninText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qeydiyyat.
        /// </summary>
        public static string SignUpPanelTitle {
            get {
                return ResourceManager.GetString("SignUpPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qeydiyyat.
        /// </summary>
        public static string SignUpText {
            get {
                return ResourceManager.GetString("SignUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt kateqoriya.
        /// </summary>
        public static string SubCategoryText {
            get {
                return ResourceManager.GetString("SubCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göndər.
        /// </summary>
        public static string SubmitText {
            get {
                return ResourceManager.GetString("SubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        public static string SurnameText {
            get {
                return ResourceManager.GetString("SurnameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter link.
        /// </summary>
        public static string TwitterLinkText {
            get {
                return ResourceManager.GetString("TwitterLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universitet.
        /// </summary>
        public static string UniversityText {
            get {
                return ResourceManager.GetString("UniversityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurs yükləyin.
        /// </summary>
        public static string UploadCourseText {
            get {
                return ResourceManager.GetString("UploadCourseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string VideoFileText {
            get {
                return ResourceManager.GetString("VideoFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videonun adı.
        /// </summary>
        public static string VideoNameText {
            get {
                return ResourceManager.GetString("VideoNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string VideoText {
            get {
                return ResourceManager.GetString("VideoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video yükləyin.
        /// </summary>
        public static string VideoUploadText {
            get {
                return ResourceManager.GetString("VideoUploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kursun məqsədi.
        /// </summary>
        public static string WhatObjectives {
            get {
                return ResourceManager.GetString("WhatObjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kursun məqsədi nədir?.
        /// </summary>
        public static string WhatObjectivesText {
            get {
                return ResourceManager.GetString("WhatObjectivesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bacarıqlar.
        /// </summary>
        public static string WhatSkills {
            get {
                return ResourceManager.GetString("WhatSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hansı bacarıqları öyrənəcəksiniz?.
        /// </summary>
        public static string WhatSkillsText {
            get {
                return ResourceManager.GetString("WhatSkillsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Kim üçün&quot; xanası.
        /// </summary>
        public static string WhoShouldTake {
            get {
                return ResourceManager.GetString("WhoShouldTake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kurs kim üçündür?.
        /// </summary>
        public static string WhoShouldTakeText {
            get {
                return ResourceManager.GetString("WhoShouldTakeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş yeri.
        /// </summary>
        public static string WorkplaceText {
            get {
                return ResourceManager.GetString("WorkplaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizimlə işləyin.
        /// </summary>
        public static string WorkWithUsText {
            get {
                return ResourceManager.GetString("WorkWithUsText", resourceCulture);
            }
        }
    }
}
